// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltcfzjlencogiibrzgpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0Y2Z6amxlbmNvZ2lpYnJ6Z3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNjcxOTUsImV4cCI6MjA0OTY0MzE5NX0.gC6GsPakCSMNg-7HoQH6wYdk9ALyD3deptr3kBcQjb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);